services:
 - docker
 
before_script:
 # fail on any non-zero exit value
 - set -e
 
 # install docker-compose
 - sudo -i curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /bin/docker-compose
 - sudo chmod +x /bin/docker-compose
 
script:
 - cd docker
 - cp ../.travis/docker-compose.env .env
 - /bin/docker-compose --file wikispeech-dev.yml build
 - /bin/docker-compose --file wikispeech-dev.yml create
 - /bin/docker-compose --file wikispeech-dev.yml up --abort-on-container-exit &
 - export pid=$!
 - echo "wikispeech server running on pid $pid"
 - sleep 300
 - sh ../.travis/exit_server_and_fail_if_not_running.sh wikispeech $pid
