services:
 - docker
 
before_script:
 - sudo -i curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /bin/docker-compose
 
script:
 - cd docker
 - /bin/docker-compose --file wikispeech.yml up &
 - echo "NO TESTS IMPLEMENTED YET => FAIL FOR NOW" && exit 1
