services:
 - docker
 
before_script:
 - sudo -i curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /bin/docker-compose
 - sudo chmod +x /bin/docker-compose
 
script:
 - cd docker
 - cp travis.env .env
 - /bin/docker-compose --file wikispeech.yml build
 - /bin/docker-compose --file wikispeech.yml create
 - /bin/docker-compose --file pronlex-import-for-ws-tests.yml up 
 - /bin/docker-compose --file wikispeech.yml up --abort-on-container-exit &
 - sleep 60
 - /bin/docker-compose --file wikispeech.yml down
 
 # - echo "TRAVIS TESTS ARE NOT COMPLETED => WILL ALWAYS FAIL FOR NOW" && exit 1
