## docker-compose configuration for importing standard lexicon data

version: '3'
services:
  pronlex:
    build: https://github.com/stts-se/pronlex.git
    image: "pronlex"
    volumes:
     - ${LEXDATA_DIR}:/appdir
    command: ["import_for_ws_tests", "/appdir", "${LEXDATA_DIR}"]
