## docker-compose configuration for importing standard lexicon data

version: '3'
services:
  pronlex:
    image: "sttsse/pronlex:$RELEASE"
    volumes:
     - ${LEXDATA_DIR}:/wikispeech/appdir
    command: ["/wikispeech/bin/import_all", "/wikispeech/appdir", "${LEXDATA_DIR}"]
