## docker-compose configuration for starting the wikispeech server with mishkal (work in progress)

version: '3'

networks:
  wikispeech:
   driver: bridge
   ipam:
     driver: default
     config:
     - subnet: 172.91.0.0/16

services:

  pronlex:
    # build: https://github.com/stts-se/pronlex.git
    image: "sttsse/pronlex:$RELEASE"
    volumes:
     - ${LEXDATA_DIR}:/appdir
    ports:
     - "8787:8787"
    networks:
     wikispeech:
       ipv4_address: 172.91.0.2
    extra_hosts:
     - "localhost:172.91.0.1"

  marytts:
    # build: https://github.com/HaraldBerthelsen/marytts.git
    image: "sttsse/marytts:$RELEASE"
    ports:
      - "59125:59125"
    networks:
     wikispeech:
       ipv4_address: 172.91.0.3
    extra_hosts:
     - "localhost:172.91.0.1"

  wikispeech:
    # build: https://github.com/stts-se/wikispeech_mockup.git
    image: "sttsse/wikispeech:$RELEASE"
    ports:
     - "10000:10000"
    depends_on:
      - pronlex
      - marytts
    networks:
     wikispeech:
       ipv4_address: 172.91.0.4
    extra_hosts:
     - "localhost:172.91.0.1"
    command: ["/bin/ws-postponed-start", "localhost:8787", "localhost:59125", "${EXTERNAL_HOST}:10000"]

