## docker-compose configuration for starting the wikispeech server

version: '3'
networks:
  wikispeech:
   driver: bridge
   ipam:
     driver: default
     config:
     - subnet: 172.99.0.0/16
services:
  pronlex:
    build: https://github.com/stts-se/pronlex.git
    image: "pronlex"
    #image: "sttsse/pronlex:version-0.2.1"
    volumes:
     - ${LEXDATA_DIR}:/go/appdir
    ports:
     - "8787:8787"
    networks:
     wikispeech:
       ipv4_address: 172.99.0.2
  marytts:
    #build: https://github.com/HaraldBerthelsen/marytts.git
    build: https://github.com/HannaLindgren/marytts.git
    image: "marytts"
    ports:
      - "59125:59125"
    networks:
     wikispeech:
       ipv4_address: 172.99.0.3
  # wikispeech_base (included automatically from hub.docker.com): https://github.com/stts-se/wikispeech_base.git
  wikispeech:
    build: https://github.com/stts-se/wikispeech_mockup.git
    image: "wikispeech"
    ports:
     - "10000:10000"
    depends_on:
      - pronlex
      - marytts
    networks:
     wikispeech:
       ipv4_address: 172.99.0.4
    command: ["/bin/ws-postponed-start", "172.99.0.1:8787", "172.99.0.1:59125"]
