## docker-compose configuration for starting the wikispeech server

version: '3'
networks:
  wikispeech:
   driver: bridge
   ipam:
     driver: default
     config:
     - subnet: 172.99.0.0/16
services:
  pronlex:
    build: https://github.com/stts-se/pronlex.git
    image: "pronlex"
    volumes:
     - ${LEXDATA_DIR}:/go/appdir
    ports:
     - "8787:8787"
    networks:
     wikispeech:
       ipv4_address: 172.99.0.2
  marytts:
    build: ${WIKISPEECH_COMPOSE_GIT}/marytts
    image: "marytts"
    ports:
      - "59125:59125"
    networks:
     wikispeech:
       ipv4_address: 172.99.0.3
  wikispeech:
    build: https://github.com/stts-se/wikispeech_mockup.git
    image: "wikispeech"
    volumes:
     - ${WIKISPEECH_COMPOSE_GIT}/docker/ws-config:/ws-config
     - ${WIKISPEECH_COMPOSE_GIT}/docker/bin:/docker/bin
    ports:
     - "10000:10000"
    depends_on:
      - pronlex
      - marytts
    networks:
     wikispeech:
       ipv4_address: 172.99.0.4
    command: ["/docker/bin/ws-postponed-start", "172.99.0.1:8787", "172.99.0.1:59125"]
    #command: ["/docker/bin/debug", "${WIKISPEECH_COMPOSE_GIT}"]
