## docker-compose configuration for starting the wikispeech server

version: '3'
networks:
  app_net:
   driver: bridge
   ipam:
     driver: default
     config:
     - subnet: 172.99.0.0/16
services:
  pronlex:
    #build: ${GOPATH}/src/github.com/stts-se/pronlex
    build: https://github.com/stts-se/pronlex.git
    image: "pronlex"
    volumes:
     - ${LEXDATA_DIR}:/go/appdir
    ports:
     - "8787:8787"
    networks:
     app_net:
       ipv4_address: 172.99.0.2
  marytts:
    build: ${WIKISPEECH_GIT}/docker/marytts
    image: "marytts"
    ports:
      - "59125:59125"
    networks:
     app_net:
       ipv4_address: 172.99.0.3
  wikispeech:
    build: ${WIKISPEECH_GIT}/docker/wikispeech
    image: "wikispeech"
    volumes:
     - ${WIKISPEECH_GIT}/docker/ws-config:/ws-config
     - ${WIKISPEECH_GIT}/docker/compose/bin:/compose/bin
    ports:
     - "10000:10000"
    depends_on:
      - pronlex
      - marytts
    networks:
     app_net:
       ipv4_address: 172.99.0.4
    command: ["/compose/bin/ws-postponed-start", "172.99.0.1:8787", "172.99.0.1:59125"]
    #command: ["/compose/bin/debug", "${WIKISPEECH_GIT}"]
